const BASE_URL='https://goplay-dzlr.onrender.com';const actor=JSON.parse(localStorage.getItem('usuarioLogado')||'null');let sid=0,lista=[],filtro='',atual=null,produtos=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const role=()=>actor.tipo==='DONO_SOCIETY'?'DONO':actor.funcao||'';const canItems=()=>['DONO','ADMIN','CAIXA','BAR'].includes(role());const canPay=()=>['DONO','ADMIN','CAIXA'].includes(role());
async function api(u,o={}){const r=await fetch(u,o),t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.error||t||'Erro');return d;}
function setFiltro(f){filtro=f;renderLista();}
function renderKPIs(){cxAbertas.textContent=lista.filter(c=>c.status==='ABERTA').length;cxFechadas.textContent=lista.filter(c=>c.status==='FECHADA').length;const hoje=new Date().toDateString();cxPagas.textContent=lista.filter(c=>c.status==='PAGA'&&new Date(c.pagaEm||c.updatedAt).toDateString()===hoje).length;cxValor.textContent=money(lista.filter(c=>['ABERTA','FECHADA'].includes(c.status)).reduce((s,c)=>s+Number(c.total||0),0));}
function renderLista(){const l=filtro?lista.filter(c=>c.status===filtro):lista;cxLista.innerHTML=l.length?l.map(c=>`<div class="f3-row" onclick="abrir(${c.id})" style="cursor:pointer"><div><strong>#${esc(c.codigo||c.id)} — ${esc(c.usuario?.nome||'Cliente')}</strong><small>${esc(c.status)} • ${c.itens?.length||0} item(ns)</small></div><strong>${money(c.total)}</strong></div>`).join(''):'<div class="f3-empty">Nenhuma comanda.</div>';}
async function abrir(id){atual=await api(`${BASE_URL}/comanda/${id}`);cxDetalheTitulo.textContent=`Comanda #${atual.codigo||atual.id} — ${atual.usuario?.nome||'Cliente'}`;renderDetalhe();}
function renderDetalhe(){if(!atual)return;const itens=atual.itens||[];cxDetalhe.innerHTML=`<div class="f3-list">${itens.length?itens.map(i=>`<div class="f3-row"><div><strong>${esc(i.nomeProduto)}</strong><small>${i.quantidade} × ${money(i.precoUnitario)}</small></div><strong>${money(i.total)}</strong></div>`).join(''):'<div class="f3-empty">Sem itens.</div>'}</div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:16px"><strong>Total</strong><strong style="font-size:24px;color:#052845">${money(atual.total)}</strong></div><div class="f3-actions" style="margin-top:14px">${atual.status==='ABERTA'&&canItems()?`<button class="f3-btn green" onclick="toggleProdutos()">+ Adicionar item</button><button class="f3-btn" onclick="fecharAtual()">Fechar comanda</button>`:''}${atual.status==='FECHADA'&&canPay()?`<button class="f3-btn green" onclick="confirmarPagamentoAtual()">Confirmar pagamento</button>`:''}</div><div id="cxProdutos" style="display:none"></div>${actor.tipo==='FUNCIONARIO'&&role()==='RECEPCAO'?'<div class="f3-role-note">Recepção possui visualização da comanda, mas não movimenta itens nem confirma pagamentos.</div>':''}`;}
async function toggleProdutos(){const box=document.getElementById('cxProdutos');if(box.style.display==='block'){box.style.display='none';return;}if(!produtos.length)produtos=await api(`${BASE_URL}/cardapio/society/${sid}`);box.style.display='block';box.innerHTML=`<h4>Adicionar produto</h4><div class="f3-products">${produtos.map(p=>`<button class="f3-product" onclick="addItem(${p.id})"><strong>${esc(p.nome)}</strong><span>${money(p.preco)}</span></button>`).join('')}</div>`;}
async function addItem(pid){const q=Number(prompt('Quantidade:','1')||0);if(!q)return;try{await api(`${BASE_URL}/comanda/${atual.id}/item`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cardapioId:pid,quantidade:q})});await abrir(atual.id);await carregarLista();}catch(e){alert(e.message);}}
async function fecharAtual(){if(!confirm('Fechar esta comanda?'))return;try{await api(`${BASE_URL}/comanda/${atual.id}/fechar`,{method:'POST'});await api(`${BASE_URL}/comanda/${atual.id}/gerar-pagamento`,{method:'POST'});await carregarLista();await abrir(atual.id);}catch(e){alert(e.message);}}
async function confirmarPagamentoAtual(){if(!confirm(`Confirmar recebimento de ${money(atual.total)}?`))return;try{await api(`${BASE_URL}/comanda/${atual.id}/pagar`,{method:'POST'});await carregarLista();await abrir(atual.id);alert('Pagamento confirmado.');}catch(e){alert(e.message);}}
async function carregarLista(){lista=await api(`${BASE_URL}/comanda/society/${sid}`);renderKPIs();renderLista();}
async function carregarTudo(){if(window.GoPlayEmpresaContextReady)await window.GoPlayEmpresaContextReady;sid=Number(localStorage.getItem('societyId')||0);if(!sid)throw new Error('Selecione uma empresa.');perfilOperacao.textContent=actor.tipo==='FUNCIONARIO'?`Perfil: ${role()} — ações limitadas conforme permissão.`:'Proprietário — acesso completo à operação.';produtos=[];await carregarLista();}
document.addEventListener('DOMContentLoaded',()=>carregarTudo().catch(e=>alert(e.message)));
