const BASE_URL='https://goplay-dzlr.onrender.com';
const actor=JSON.parse(localStorage.getItem('usuarioLogado')||'null');
let sid=0,lista=[],filtro='ativas',atual=null,produtos=[],busy=false,openVersion=0,listVersion=0,clientVersion=0;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const labels={ABERTA:'Em atendimento',FECHAMENTO_SOLICITADO:'Pediu fechamento',FECHADA:'Aguardando pagamento',PAGA:'Paga',CANCELADA:'Cancelada'};
const role=()=>actor?.tipo==='DONO_SOCIETY'?'DONO':actor?.funcao||'';
const canItems=()=>['DONO','ADMIN','CAIXA','BAR'].includes(role());
const canPay=()=>['DONO','ADMIN','CAIXA'].includes(role());
async function api(path,o={}){const r=await fetch(BASE_URL+path,o),t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.error||'Não foi possível concluir a operação.');return d;}
function feedback(text,error=false){$('cxStatus').textContent=text;$('cxStatus').classList.toggle('error',error);}
function showError(e){feedback(e.message,true);}
function setFiltro(f){filtro=f;renderLista();}
function localDay(v){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date(v));}
function renderKPIs(){const paid=lista.filter(c=>c.status==='PAGA'&&localDay(c.pagaEm||c.updatedAt)===localDay(new Date()));$('cxAbertas').textContent=lista.filter(c=>['ABERTA','FECHAMENTO_SOLICITADO'].includes(c.status)).length;$('cxFechadas').textContent=lista.filter(c=>c.status==='FECHADA').length;$('cxPagas').textContent=paid.length;$('cxRecebido').textContent=money(paid.reduce((s,c)=>s+Number(c.total||0),0));$('cxValor').textContent=money(lista.filter(c=>['ABERTA','FECHAMENTO_SOLICITADO','FECHADA'].includes(c.status)).reduce((s,c)=>s+Number(c.total||0),0));}
function renderLista(){const q=$('cxBusca').value.trim().toLocaleLowerCase('pt-BR');const l=lista.filter(c=>(filtro==='ativas'?['ABERTA','FECHAMENTO_SOLICITADO'].includes(c.status):filtro==='historico'?['PAGA','CANCELADA'].includes(c.status):!filtro||c.status===filtro)&&(!q||`${c.usuario?.nome||''} ${c.codigo||c.id}`.toLocaleLowerCase('pt-BR').includes(q))).sort((a,b)=>Number(b.status==='FECHAMENTO_SOLICITADO')-Number(a.status==='FECHAMENTO_SOLICITADO'));$('cxListCount').textContent=l.length;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filtro)));$('cxLista').innerHTML=l.length?l.map(c=>`<button type="button" class="cx-tab-row ${atual?.id===c.id?'selected':''}" onclick="abrir(${c.id}).catch(showError)"><span><strong>${esc(c.usuario?.nome||'Cliente')}</strong><small>#${esc(c.codigo||c.id)} · ${c.itens?.reduce((n,i)=>n+i.quantidade,0)||0} itens</small><small class="cx-badge ${esc(c.status)}">${esc(labels[c.status]||c.status)}</small></span><strong>${money(c.total)}</strong></button>`).join(''):'<div class="f3-empty">Nenhuma comanda neste filtro.</div>';}
async function abrir(id,internal=false){if((busy&&!internal)||($('cxCheckout').open&&atual?.id!==id))return;const version=++openVersion,data=await api(`/comanda/${id}`);if(version!==openVersion||data.societyId!==sid)return;atual=data;$('cxDetalheTitulo').textContent=`${atual.usuario?.nome||'Cliente'} · #${atual.codigo||atual.id}`;renderDetalhe();renderLista();}
function renderDetalhe(){if(!atual)return;const active=atual.status==='ABERTA',closable=['ABERTA','FECHAMENTO_SOLICITADO'].includes(atual.status);$('cxDetalhe').innerHTML=`<span class="cx-badge ${esc(atual.status)}">${esc(labels[atual.status]||atual.status)}</span><div class="cx-cart-total"><span>Total da comanda</span>${money(atual.total)}</div><div class="cx-cart">${atual.itens?.length?atual.itens.map(i=>`<div class="cx-item"><div><strong>${esc(i.nomeProduto)}</strong><small>${i.quantidade} × ${money(i.precoUnitario)}</small></div><div class="f3-actions"><strong>${money(i.total)}</strong>${active&&canItems()?`<button type="button" class="cx-remove" aria-label="Remover ${esc(i.nomeProduto)}" onclick="removerItem(${i.id})">×</button>`:''}</div></div>`).join(''):'<div class="f3-empty">Toque em um produto abaixo para começar.</div>'}</div><div class="f3-actions" style="margin-top:18px">${closable&&canItems()?`<button type="button" class="f3-btn green" onclick="fecharAtual()" ${!atual.itens?.length?'disabled':''}>${canPay()?'Fechar / receber':'Conferir e fechar'}</button>`:''}${atual.status==='FECHADA'&&canPay()?'<button type="button" class="f3-btn green" onclick="confirmarPagamentoAtual()">Confirmar recebimento</button>':''}</div>${active&&canItems()?'<section class="cx-catalog"><h3>Lançar produtos</h3><div class="cx-catalog-tools"><input id="cxProdutoBusca" class="f3-input" type="search" placeholder="Buscar produto" aria-label="Buscar produto" oninput="renderProdutos()"><label>Qtd. <input id="cxQuantidade" type="number" min="1" max="999" step="1" value="1"></label></div><div id="cxProdutos" class="cx-product-grid">Carregando cardápio…</div></section>':''}${!canItems()?'<p class="f3-role-note">Seu perfil permite consultar comandas. Lançamentos e recebimentos são feitos pelos perfis autorizados.</p>':''}`;if(active&&canItems()){const catalog=$('cxDetalhe').querySelector('.cx-catalog');$('cxDetalhe').querySelector('.cx-cart').before(catalog);renderProdutos();}}
function renderProdutos(){const root=$('cxProdutos');if(!root)return;const q=$('cxProdutoBusca').value.trim().toLocaleLowerCase('pt-BR');const list=produtos.filter(p=>p.nome.toLocaleLowerCase('pt-BR').includes(q));root.innerHTML=list.length?list.map(p=>`<button type="button" class="cx-product" onclick="addItem(${p.id})"><strong>${esc(p.nome)}</strong><span>${money(p.preco)} <b>＋</b></span></button>`).join(''):'<p class="f3-empty">Nenhum produto encontrado no cardápio.</p>';}
async function mutate(fn,success){if(busy||!atual)return;busy=true;const id=atual.id;const productQuery=$('cxProdutoBusca')?.value||'',quantity=$('cxQuantidade')?.value||'1';const buttons=[...document.querySelectorAll('#cxDetalhe button,#cxCheckout button')];buttons.forEach(b=>b.disabled=true);try{await fn(id);feedback(success);await carregarLista();await abrir(id,true);if($('cxProdutoBusca')){$('cxProdutoBusca').value=productQuery;$('cxQuantidade').value=quantity;renderProdutos();}return true;}catch(e){showError(e);return false;}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
async function addItem(pid){const q=Number($('cxQuantidade')?.value);if(!Number.isInteger(q)||q<1||q>999){feedback('Informe uma quantidade inteira entre 1 e 999.',true);return;}await mutate(id=>api(`/comanda/${id}/item`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cardapioId:pid,quantidade:q})}),'Produto lançado na comanda.');}
async function removerItem(id){if(!confirm('Remover este lançamento da comanda?'))return;await mutate(()=>api(`/comanda/item/${id}`,{method:'DELETE'}),'Lançamento removido.');}
async function fecharAtual(){if(busy||!atual||!canItems()||!atual.itens?.length)return;try{await abrir(atual.id);}catch(e){showError(e);return;}if(!["ABERTA","FECHAMENTO_SOLICITADO"].includes(atual.status))return;$('cxCheckoutCliente').textContent=`${atual.usuario?.nome||'Cliente'} · Comanda #${atual.codigo||atual.id}`;$('cxCheckoutTotal').textContent=money(atual.total);$('cxReceberAgora').hidden=!canPay();$('cxCheckoutStatus').textContent='';$('cxCheckout').showModal();}
async function finalizarComanda(receber){if(receber&&!canPay())return;const ok=await mutate(async id=>{if(['ABERTA','FECHAMENTO_SOLICITADO'].includes(atual.status)){await api(`/comanda/${id}/fechar`,{method:'POST'});atual.status='FECHADA';}await api(`/comanda/${id}/gerar-pagamento`,{method:'POST'});if(receber)await api(`/comanda/${id}/pagar`,{method:'POST'});},receber?'Comanda fechada e pagamento confirmado.':'Comanda fechada. Aguardando pagamento.');if(ok)$('cxCheckout').close();else $('cxCheckoutStatus').textContent=$('cxStatus').textContent;}
async function confirmarPagamentoAtual(){if(!canPay()||!confirm(`Confirmar recebimento de ${money(atual.total)}?`))return;await mutate(async id=>{if(!atual.pagamento)await api(`/comanda/${id}/gerar-pagamento`,{method:'POST'});await api(`/comanda/${id}/pagar`,{method:'POST'});},'Pagamento confirmado.');}
function novaComanda(){if(!canItems()||!sid)return;$('cxClientes').innerHTML='';$('cxClienteStatus').textContent='';$('cxClienteBusca').value='';$('cxNewDialog').showModal();$('cxClienteBusca').focus();}
async function buscarClientes(){const q=$('cxClienteBusca').value.trim(),version=++clientVersion;if(q.length<2){$('cxClienteStatus').textContent='Digite pelo menos 2 letras.';return;}$('cxClienteStatus').textContent='Buscando…';try{const data=await api(`/jogadores/perfis?q=${encodeURIComponent(q)}&take=12`);if(version!==clientVersion)return;$('cxClientes').innerHTML=data.usuarios.map(p=>`<button type="button" class="cx-tab-row" onclick="abrirParaCliente(${p.id})"><strong>${esc(p.nome)}</strong><span>Abrir →</span></button>`).join('');$('cxClienteStatus').textContent=data.usuarios.length?'Selecione o cliente para abrir ou retomar a comanda.':'Nenhum cliente encontrado.';}catch(e){$('cxClienteStatus').textContent=e.message;}}
async function abrirParaCliente(usuarioId){if(busy)return;busy=true;try{const c=await api('/comanda',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usuarioId,societyId:sid})});$('cxNewDialog').close();filtro='ativas';$('cxBusca').value='';feedback(c.reutilizada?'Comanda existente retomada.':'Comanda aberta.');busy=false;await carregarLista();await abrir(c.id);}catch(e){$('cxClienteStatus').textContent=e.message;}finally{busy=false;}}
async function carregarLista(){if(!sid)return;const version=++listVersion,data=await api(`/comanda/society/${sid}`);if(version!==listVersion)return;lista=data;renderKPIs();renderLista();}
async function carregarTudo(){if(window.GoPlayEmpresaContextReady)await window.GoPlayEmpresaContextReady;const selected=Number(localStorage.getItem('societyId')||actor?.societyId||0);if(!selected)throw new Error('Selecione uma empresa para atender.');if(selected!==sid){++openVersion;atual=null;$('cxDetalheTitulo').textContent='Comece pelo cliente';$('cxDetalhe').innerHTML='<div class="f3-empty">Selecione uma comanda para atender.</div>';}sid=selected;$('perfilOperacao').textContent=`${localStorage.getItem('societyContextName')||'Empresa selecionada'} · ${role()==='DONO'?'Atendimento e recebimentos':role()}`;$('cxNova').hidden=!canItems();await carregarLista();if(canItems())produtos=await api(`/cardapio/society/${sid}`);if(atual)await abrir(atual.id);feedback('Caixa atualizado.');}
document.addEventListener('DOMContentLoaded',()=>{carregarTudo().catch(showError);$('cxClienteBusca').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();buscarClientes();}});const timer=setInterval(()=>{if(!busy&&!document.hidden)carregarLista().catch(showError);},10000);window.addEventListener('beforeunload',()=>clearInterval(timer),{once:true});});
