const BASE_URL='https://goplay-dzlr.onrender.com';let sid=0;
const roleName={ADMIN:'Administrador',MESARIO:'Mesário',CAIXA:'Caixa',BAR:'Bar',RECEPCAO:'Recepção'};
async function api(url,opt={}){const r=await fetch(url,opt),t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.error||t||'Erro');return d;}
async function carregar(){if(window.GoPlayEmpresaContextReady)await window.GoPlayEmpresaContextReady;sid=Number(localStorage.getItem('societyId')||0);if(!sid)return alert('Selecione uma empresa.');const lista=await api(`${BASE_URL}/society/${sid}/funcionarios`);document.getElementById('listaFuncionarios').innerHTML=lista.length?lista.map(f=>`<div class="f3-row"><div><strong>${f.nome}</strong> <span class="f3-badge ${f.ativo?'ok':'off'}">${f.ativo?'ATIVO':'INATIVO'}</span><small>${f.acesso} • ${roleName[f.funcao]||f.funcao}</small></div><div class="f3-actions"><button class="f3-btn light" onclick="trocarPin(${f.id})">Novo PIN</button><button class="f3-btn light" onclick="revogar(${f.id})">Revogar sessões</button><button class="f3-btn ${f.ativo?'danger':'green'}" onclick="alternar(${f.id},${!f.ativo})">${f.ativo?'Desativar':'Ativar'}</button></div></div>`).join(''):'<div class="f3-empty">Nenhum funcionário cadastrado.</div>';}
async function criar(){const body={nome:fNome.value.trim(),acesso:fAcesso.value.trim(),funcao:fFuncao.value,pin:fPin.value.trim()};try{await api(`${BASE_URL}/society/${sid}/funcionarios`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});fNome.value=fAcesso.value=fPin.value='';await carregar();alert('Acesso criado.');}catch(e){alert(e.message);}}
async function alternar(id,ativo){try{await api(`${BASE_URL}/society/${sid}/funcionarios/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ativo})});carregar();}catch(e){alert(e.message);}}
async function trocarPin(id){const pin=prompt('Novo PIN (mínimo 4 dígitos):');if(!pin)return;try{await api(`${BASE_URL}/society/${sid}/funcionarios/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});alert('PIN alterado e sessões antigas revogadas.');}catch(e){alert(e.message);}}
async function revogar(id){if(!confirm('Revogar todas as sessões atuais deste funcionário?'))return;try{await api(`${BASE_URL}/society/${sid}/funcionarios/${id}/revogar`,{method:'POST'});alert('Sessões revogadas.');}catch(e){alert(e.message);}}
document.getElementById('btnCriarFuncionario').onclick=criar;document.addEventListener('DOMContentLoaded',()=>carregar().catch(e=>alert(e.message)));
