const BASE_URL='https://goplay-dzlr.onrender.com';
const user=JSON.parse(localStorage.getItem('usuarioLogado')||'null');
const groupId=Number(new URLSearchParams(location.search).get('grupoId')||0); const $=id=>document.getElementById(id); const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
async function api(url,opt={}){const r=await fetch(url,opt),t=await r.text().catch(()=>"");let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.error||t||`HTTP ${r.status}`);return d;}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); const date=v=>new Date(v).toLocaleDateString('pt-BR');
let group=null;
function countStatus(a,s){return (a?.presencas||[]).filter(p=>p.status===s).length;}
async function render(){group=await api(`${BASE_URL}/grupos-horario/${groupId}`);const future=group.agendamentos.filter(a=>new Date(a.data)>=new Date(new Date().setHours(0,0,0,0)));const next=future[0];
 $('grupoHero').innerHTML=`<div><h2>${esc(group.nome)}</h2><p>📍 ${esc(group.society.nome)} • Organizador: ${esc(group.organizador.nome)}</p></div><div class="phase4-actions"><button class="p4-btn p4-secondary" onclick="location.href='meus-horarios.html'">Voltar</button></div>`;
 $('grupoResumo').innerHTML=`<div class="p4-topline"><span class="p4-chip">👥 ${group.membros.length}/${group.maxJogadores}</span><span class="p4-chip">${group.ativo?'Ativo':'Inativo'}</span></div><p class="p4-muted" style="margin-top:10px">${esc(group.descricao||'Sem descrição.')}</p>`;
 $('proximoJogo').innerHTML=next?`<strong>${date(next.data)} • ${esc(next.horaInicio)}-${esc(next.horaFim)}</strong><div class="p4-topline" style="margin-top:10px"><span class="p4-chip yes">👍 ${countStatus(next,'VOU')}</span><span class="p4-chip no">👎 ${countStatus(next,'NAO_VOU')}</span><span class="p4-chip wait">⏳ ${countStatus(next,'PENDENTE')}</span></div><button class="p4-btn p4-primary" style="margin-top:12px" onclick="location.href='confirmar-presenca.html?agendamentoId=${next.id}'">Abrir confirmação</button>`:'<div class="p4-muted">Ainda não existe encontro futuro.</div>';
 const hf=group.horariosFixos[0]; $('grupoCobranca').innerHTML=hf?`${hf.tipoCobranca==='MENSAL'?`<div class="p4-money">${money(hf.valorMensal)}/mês</div><div class="p4-muted">Mensalista</div>`:`<div class="p4-money">${money(hf.valorPorJogo)}</div><div class="p4-muted">Por jogo</div>`}<div class="p4-topline" style="margin-top:8px"><span class="p4-chip ${hf.status==='APROVADO'?'yes':hf.status==='RECUSADO'?'no':'wait'}">${hf.status==='APROVADO'?'✓ Aprovado':hf.status==='RECUSADO'?'✕ Recusado':'⏳ Aguardando empresa'}</span></div><div class="p4-muted" style="margin-top:8px">${hf.dividirValor?'Valor pode ser dividido entre confirmados.':'Sem rateio automático.'}</div>${group.podeAprovarHorario&&hf.status==='PENDENTE'?`<div class="phase4-actions" style="margin-top:10px"><button class="p4-btn p4-primary" onclick="aprovarHorario(${hf.id})">Aprovar</button><button class="p4-btn p4-danger" onclick="recusarHorario(${hf.id})">Recusar</button></div>`:''}`:'<div class="p4-muted">Configure o horário fixo abaixo.</div>';
 $('membrosLista').innerHTML=group.membros.map(m=>`<div class="p4-row"><div style="display:flex;gap:10px;align-items:center"><div class="p4-avatar">${m.usuario.fotoUrl?`<img src="${esc(m.usuario.fotoUrl)}" style="width:100%;height:100%;border-radius:50%;object-fit:cover">`:esc(m.usuario.nome[0]||'?')}</div><div><strong>${esc(m.usuario.nome)}</strong><div class="p4-muted">${esc(m.usuario.posicaoCampo||m.usuario.email||'Jogador')}</div></div></div>${group.podeGerenciar&&m.usuarioId!==group.organizadorId?`<button class="p4-btn p4-danger" onclick="remover(${m.usuarioId})">Remover</button>`:m.usuarioId===group.organizadorId?'<span class="p4-chip">Organizador</span>':''}</div>`).join('');
 $('inviteControls').style.display=group.podeGerenciar?'grid':'none'; $('criarHorarioBox').style.display=group.podeGerenciar&&!(hf&&hf.status==='PENDENTE')?'block':'none';
 $('encontrosLista').innerHTML=future.length?future.slice(0,20).map(a=>`<div class="p4-row"><div class="p4-row-main"><strong>${date(a.data)} • ${esc(a.horaInicio)}-${esc(a.horaFim)}</strong><div class="p4-muted">${esc(a.campo?.nome||'Quadra')}</div><div class="p4-topline" style="margin-top:6px"><span class="p4-chip yes">👍 ${countStatus(a,'VOU')}</span><span class="p4-chip no">👎 ${countStatus(a,'NAO_VOU')}</span><span class="p4-chip wait">⏳ ${countStatus(a,'PENDENTE')}</span></div></div><button class="p4-btn p4-dark" onclick="location.href='confirmar-presenca.html?agendamentoId=${a.id}'">Detalhes</button></div>`).join(''):'<div class="p4-empty">Nenhum encontro futuro.</div>';
 if(group.podeGerenciar&&group.horariosFixos.some(h=>h.tipoCobranca==='MENSAL'&&h.status==='APROVADO'))$('btnGerarMensalidade').style.display='inline-block';
 if(group.podeGerenciar)await loadFields();
}
async function loadFields(){const fields=await api(`${BASE_URL}/campos/society/${group.societyId}`);$('hfCampo').innerHTML='<option value="">Selecione</option>'+fields.map(c=>`<option value="${c.id}" data-avulso="${c.valorAvulso||0}" data-mensal="${c.valorMensal||0}">${esc(c.nome)}</option>`).join('');$('hfCampo').onchange=()=>{const o=$('hfCampo').selectedOptions[0];if(o){$('hfValorJogo').value=o.dataset.avulso||'';$('hfValorMensal').value=o.dataset.mensal||'';}};if(!$('hfInicio').value)$('hfInicio').value=new Date().toISOString().slice(0,10);}
window.remover=async uid=>{if(!confirm('Remover este jogador do grupo?'))return;try{await api(`${BASE_URL}/grupos-horario/${groupId}/membros/${uid}`,{method:'DELETE'});await render();}catch(e){alert(e.message);}};
$('btnConvidarEmail')?.addEventListener('click',async()=>{const emails=$('inviteEmail').value.split(/[,;\s]+/).map(x=>x.trim()).filter(Boolean);if(!emails.length)return alert('Informe pelo menos um e-mail.');let ok=0,erros=[];for(const email of emails){try{await api(`${BASE_URL}/grupos-horario/${groupId}/convidar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});ok++;}catch(e){erros.push(`${email}: ${e.message}`);}}$('inviteEmail').value='';await render();alert(`${ok} jogador(es) convidado(s) pelo sininho.${erros.length?`\n\nNão enviados:\n${erros.join('\n')}`:''}`);});
$('btnBuscarDisponiveis')?.addEventListener('click',async()=>{try{const users=await api(`${BASE_URL}/grupos-horario/${groupId}/disponiveis`);$('disponiveisBox').style.display='block';$('disponiveisLista').innerHTML=users.length?users.map(u=>`<div class="p4-row"><div><strong>${esc(u.nome)}</strong><div class="p4-muted">${esc(u.posicaoCampo||'Jogador disponível')}</div></div><button class="p4-btn p4-primary" onclick="convidarDisponivel(${u.id})">Convidar</button></div>`).join(''):'<div class="p4-empty">Nenhum jogador marcou disponibilidade no momento.</div>';}catch(e){alert(e.message);}});
$('btnFecharDisponiveis')?.addEventListener('click',()=>$('disponiveisBox').style.display='none');
window.convidarDisponivel=async uid=>{try{await api(`${BASE_URL}/grupos-horario/${groupId}/convidar`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usuarioId:uid})});await render();$('disponiveisBox').style.display='none';alert('Convite enviado pelo sininho.');}catch(e){alert(e.message);}};
$('formHorarioFixo')?.addEventListener('submit',async e=>{e.preventDefault();if(!confirm('Enviar esta recorrência? Se você não for da administração da empresa, ela precisará aprovar antes de reservar.'))return;try{const body={campoId:Number($('hfCampo').value),diaSemana:Number($('hfDia').value),dataInicio:$('hfInicio').value,horaInicio:$('hfHoraInicio').value,horaFim:$('hfHoraFim').value,semanas:Number($('hfSemanas').value||12),tipoCobranca:$('hfTipo').value,valorPorJogo:Number($('hfValorJogo').value||0),valorMensal:Number($('hfValorMensal').value||0),dividirValor:$('hfDividir').checked};const d=await api(`${BASE_URL}/grupos-horario/${groupId}/horario-fixo`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(d.pendenteAprovacao) alert('Solicitação enviada. A empresa recebeu um aviso no sininho para aprovar.'); else alert(`${d.agendamentos.length} encontros criados. Os jogadores receberam notificação.`);await render();}catch(err){alert(err.message);}});
$('btnGerarMensalidade')?.addEventListener('click',async()=>{try{const p=await api(`${BASE_URL}/grupos-horario/${groupId}/mensalidade`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});alert(`Mensalidade gerada: ${money(p.valor)}.`);}catch(e){alert(e.message);}});

window.aprovarHorario=async hfId=>{if(!confirm('Aprovar este horário fixo e reservar todas as ocorrências?'))return;try{const d=await api(`${BASE_URL}/horarios-fixos/${hfId}/aprovar`,{method:'POST'});alert(`${d.agendamentos.length} encontros aprovados e reservados.`);await render();}catch(e){alert(e.message);}};
window.recusarHorario=async hfId=>{if(!confirm('Recusar esta solicitação de horário fixo?'))return;try{await api(`${BASE_URL}/horarios-fixos/${hfId}/recusar`,{method:'POST'});alert('Solicitação recusada.');await render();}catch(e){alert(e.message);}};

document.addEventListener('DOMContentLoaded',()=>{if(!groupId)return alert('Grupo inválido.');render().catch(e=>alert(e.message));});
