const BASE_URL="https://goplay-dzlr.onrender.com";
const jogoId=Number(new URLSearchParams(location.search).get("jogoId"));
let cache=null, clockBase=0, clockStartedAt=null, clockRunning=false, reloadTimer=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
async function json(url){const r=await fetch(url);const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.error||t||`HTTP ${r.status}`);return d}
function fmt(sec){sec=Math.max(0,Math.floor(sec||0));return `${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
function clockNow(){return clockBase+(clockRunning&&clockStartedAt?Math.floor((Date.now()-clockStartedAt)/1000):0)}
function statusLabel(s){return {AGENDADO:"Agendado",AO_VIVO:"AO VIVO",INTERVALO:"Intervalo",ENCERRADO:"Encerrado"}[s]||s||"Agendado"}
function icon(tipo){return {GOL:"⚽",CARTAO_AMARELO:"🟨",CARTAO_VERMELHO:"🟥",CHUTE:"🥅",CHUTE_NO_GOL:"🎯",ESCANTEIO:"🚩",LATERAL:"↔️",FALTA:"⚠️",SUBSTITUICAO:"🔄",OBSERVACAO:"📝"}[tipo]||"•"}
function tipoLabel(tipo){return {GOL:"Gol",CARTAO_AMARELO:"Cartão amarelo",CARTAO_VERMELHO:"Cartão vermelho",CHUTE:"Chute",CHUTE_NO_GOL:"Chute no gol",ESCANTEIO:"Escanteio",LATERAL:"Lateral",FALTA:"Falta",SUBSTITUICAO:"Substituição",OBSERVACAO:"Observação"}[tipo]||tipo}
function eventText(e){if(e.tipo==="SUBSTITUICAO")return `${esc(e.jogadorSaindo?.nome||"-")} saiu • ${esc(e.jogadorEntrando?.nome||"-")} entrou`;return [e.time?.nome,e.jogador?.nome,e.detalhe].filter(Boolean).map(esc).join(" • ")}
function render(data){cache=data;const j=data.jogo;$('campeonatoNome').textContent=j.campeonato?.nome||"Partida";$('empresaNome').textContent=j.campeonato?.society?.nome||"GoPlay";$('timeA').textContent=j.timeA?.nome||"Time A";$('timeB').textContent=j.timeB?.nome||"Time B";$('placar').textContent=`${j.golsA??0} × ${j.golsB??0}`;$('periodo').textContent=j.periodo===2?"2º tempo":"1º tempo";
 const badge=$('statusBadge');badge.textContent=statusLabel(j.statusOperacao);badge.className=`live-status ${String(j.statusOperacao||"").toLowerCase().replaceAll("_","-")}`;
 if(j.desempateTipo==="PENALTIS"&&j.penaltisA!=null){$('penaltis').style.display="block";$('penaltis').textContent=`Pênaltis: ${j.timeA.nome} ${j.penaltisA} × ${j.penaltisB} ${j.timeB.nome}`}else $('penaltis').style.display="none";
 clockBase=Number(j.cronometroAtualSegundos??j.cronometroSegundos??0);clockStartedAt=Date.now();clockRunning=j.statusOperacao==="AO_VIVO"&&!j.finalizado;$('clock').textContent=fmt(clockBase);
 renderTimeline(j.eventos||[]);renderStats(j);renderLineups(j,data.elencoA||[],data.elencoB||[])}
function renderTimeline(events){const box=$('timeline');if(!events.length){box.innerHTML='<div class="empty">A partida ainda não possui eventos.</div>';return}box.innerHTML=events.map(e=>`<div class="event"><div class="event-minute">${e.minuto??0}'</div><div class="event-icon">${icon(e.tipo)}</div><div class="event-main"><strong>${tipoLabel(e.tipo)}</strong><small>${eventText(e)||"Evento da partida"}</small></div></div>`).join("")}
function renderStats(j){const a=(j.estatisticasTimes||[]).find(x=>x.timeId===j.timeAId)||{},b=(j.estatisticasTimes||[]).find(x=>x.timeId===j.timeBId)||{};const rows=[["Chutes","chutes"],["No gol","chutesNoGol"],["Escanteios","escanteios"],["Laterais","laterais"],["Faltas","faltas"],["Posse (%)","posse"]];$('stats').innerHTML=`<table class="stats-table"><thead><tr><th></th><th>${esc(j.timeA.nome)}</th><th>${esc(j.timeB.nome)}</th></tr></thead><tbody>${rows.map(([l,k])=>`<tr><td>${l}</td><td>${a[k]??0}</td><td>${b[k]??0}</td></tr>`).join("")}</tbody></table>`}
function renderLineups(j,elA,elB){const escalados=new Map((j.jogadoresAtuacao||[]).map(x=>[x.jogadorId,x]));function box(nome,el){const ativos=el.filter(p=>escalados.has(p.id));return `<div class="lineup-box"><h3>${esc(nome)}</h3>${ativos.length?ativos.map(p=>{const a=escalados.get(p.id);return `<div class="player-row">${a.titular?"⭐ ":""}${esc(p.nome)}${a.saiuMinuto!=null?` <small>• saiu ${a.saiuMinuto}'</small>`:""}</div>`}).join(""):'<div class="empty">Escalação não informada.</div>'}</div>`}$('lineups').innerHTML=box(j.timeA.nome,elA)+box(j.timeB.nome,elB)}
async function load(){if(!jogoId)throw new Error("Jogo não informado.");render(await json(`${BASE_URL}/jogo/${jogoId}`))}
function connect(){const es=new EventSource(`${BASE_URL}/jogo/${jogoId}/stream`);es.addEventListener("connected",()=>{$('realtimeNote').textContent="🟢 Atualizações em tempo real conectadas"});es.addEventListener("jogo-atualizado",()=>{clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>load().catch(console.error),150)});es.onerror=()=>{$('realtimeNote').textContent="🟠 Reconectando às atualizações…"}}
setInterval(()=>{$('clock').textContent=fmt(clockNow())},1000);document.addEventListener("DOMContentLoaded",()=>{$('btnVoltar').onclick=()=>history.length>1?history.back():location.href="campeonatos-view.html";load().then(connect).catch(e=>{$('realtimeNote').textContent=e.message})});
