const BASE_URL="https://goplay-dzlr.onrender.com";const q=new URLSearchParams(location.search),jogoId=Number(q.get("jogoId")),token=q.get("token")||"";let cache=null,timeId=null,clockBase=0,clockStartedAt=null,clockRunning=false,reloadTimer=null;const $=id=>document.getElementById(id);const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function api(url,opt={}){opt.headers={...(opt.headers||{}),"X-Mesa-Token":token};if(opt.body&&!opt.headers["Content-Type"])opt.headers["Content-Type"]="application/json";const r=await fetch(url,opt),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(d?.error||t||`HTTP ${r.status}`);return d}function msg(t){const m=$('msg');m.textContent=t;m.style.display=t?'block':'none'}function fmt(s){s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function nowClock(){return clockBase+(clockRunning&&clockStartedAt?Math.floor((Date.now()-clockStartedAt)/1000):0)}function icon(t){return {GOL:'⚽',CARTAO_AMARELO:'🟨',CARTAO_VERMELHO:'🟥',CHUTE:'🥅',CHUTE_NO_GOL:'🎯',ESCANTEIO:'🚩',LATERAL:'↔️',FALTA:'⚠️',SUBSTITUICAO:'🔄',OBSERVACAO:'📝'}[t]||'•'}
function render(d){cache=d;const j=d.jogo;timeId=timeId&&[j.timeAId,j.timeBId].includes(timeId)?timeId:j.timeAId;$('mesarioNome').textContent=`${j.mesarioNome||'Mesário'} • ${j.campeonato?.nome||'Campeonato'}`;$('timeA').textContent=j.timeA.nome;$('timeB').textContent=j.timeB.nome;$('pickA').textContent=j.timeA.nome;$('pickB').textContent=j.timeB.nome;$('placar').textContent=`${j.golsA??0} × ${j.golsB??0}`;$('status').textContent=j.statusOperacao;$('periodo').textContent=j.periodo===2?'2º tempo':'1º tempo';clockBase=Number(j.cronometroAtualSegundos??0);clockStartedAt=Date.now();clockRunning=!!j.cronometroRodando;$('clock').textContent=fmt(clockBase);$('btnEncerrar').disabled=!!j.finalizado;selectTeam(timeId,false);renderQuick();renderTimeline();renderLineups();renderStatsMini()}
function selectTeam(id,refill=true){timeId=Number(id);const j=cache?.jogo;if(!j)return;$('pickA').classList.toggle('active',timeId===j.timeAId);$('pickB').classList.toggle('active',timeId===j.timeBId);if(refill)fillPlayers();else fillPlayers()}
function roster(){const j=cache.jogo;return timeId===j.timeAId?(cache.elencoA||[]):(cache.elencoB||[])}function fillPlayers(){const p=$('jogador'),old=p.value;p.innerHTML='<option value="">Jogador (opcional)</option>'+roster().map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');if([...p.options].some(o=>o.value===old))p.value=old}
function renderQuick(){const defs=[['GOL','⚽','Gol'],['CARTAO_AMARELO','🟨','Amarelo'],['CARTAO_VERMELHO','🟥','Vermelho'],['CHUTE','🥅','Chute'],['CHUTE_NO_GOL','🎯','No gol'],['ESCANTEIO','🚩','Escanteio'],['FALTA','⚠️','Falta'],['LATERAL','↔️','Lateral']];$('quick').innerHTML=defs.map(([t,i,l])=>`<button class="event-btn" data-event="${t}"><span>${i}</span>${l}</button>`).join('');document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>addEvent(b.dataset.event))}
async function addEvent(tipo,extra={}){try{msg('');const jogadorId=Number($('jogador').value||0)||null;await api(`${BASE_URL}/jogo/${jogoId}/evento`,{method:'POST',body:JSON.stringify({tipo,timeId,jogadorId,...extra})});await load()}catch(e){msg(e.message)}}
function renderTimeline(){const ev=cache.jogo.eventos||[];$('timeline').innerHTML=ev.length?ev.map(e=>`<div class="event"><strong>${e.minuto??0}' ${icon(e.tipo)} ${e.tipo.replaceAll('_',' ')}</strong><small>${esc([e.time?.nome,e.jogador?.nome,e.detalhe].filter(Boolean).join(' • ')||(e.tipo==='SUBSTITUICAO'?`${e.jogadorSaindo?.nome||'-'} → ${e.jogadorEntrando?.nome||'-'}`:''))}</small></div>`).join(''):'<div class="muted">Nenhum evento ainda.</div>'}
function renderLineups(){const j=cache.jogo,escSet=new Set((j.jogadoresAtuacao||[]).map(x=>x.jogadorId));function box(nome,list,tId){return `<div class="lineup"><h3>${esc(nome)}</h3>${(list||[]).map(p=>`<div class="player"><span>${esc(p.nome)}</span><button class="${escSet.has(p.id)?'done':''}" data-lineup="${p.id}" data-time="${tId}" ${escSet.has(p.id)?'disabled':''}>${escSet.has(p.id)?'Escalado':'Escalar'}</button></div>`).join('')||'<div class="muted">Sem jogadores.</div>'}</div>`}$('lineups').innerHTML=box(j.timeA.nome,cache.elencoA,j.timeAId)+box(j.timeB.nome,cache.elencoB,j.timeBId);document.querySelectorAll('[data-lineup]').forEach(b=>b.onclick=async()=>{try{await api(`${BASE_URL}/jogo/${jogoId}/escalacao`,{method:'POST',body:JSON.stringify({timeId:Number(b.dataset.time),jogadorId:Number(b.dataset.lineup),titular:true})});load()}catch(e){msg(e.message)}})}
function renderStatsMini(){const j=cache.jogo,a=(j.estatisticasTimes||[]).find(x=>x.timeId===j.timeAId)||{},b=(j.estatisticasTimes||[]).find(x=>x.timeId===j.timeBId)||{};$('statsMini').innerHTML=`<div class="statbox"><span>${esc(j.timeA.nome)}</span><strong>${a.chutesNoGol||0}</strong><small>No gol • ${a.faltas||0} faltas</small></div><div class="statbox"><span>${esc(j.timeB.nome)}</span><strong>${b.chutesNoGol||0}</strong><small>No gol • ${b.faltas||0} faltas</small></div>`}
async function clock(acao){try{await api(`${BASE_URL}/jogo/${jogoId}/cronometro`,{method:'POST',body:JSON.stringify({acao})});await load()}catch(e){msg(e.message)}}
function openModal(id){$(id).classList.add('open')}function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('open'))}
async function undo(){if(!confirm('Desfazer o último evento registrado?'))return;try{await api(`${BASE_URL}/jogo/${jogoId}/evento/ultimo`,{method:'DELETE'});await load()}catch(e){msg(e.message)}}
async function finish(){if(!cache||cache.jogo.finalizado)return;if(!confirm('Encerrar esta partida? Isso atualiza a classificação do campeonato.'))return;const j=cache.jogo,payload={golsA:j.golsA??0,golsB:j.golsB??0};if(j.tipoJogo==='MATA_MATA'&&payload.golsA===payload.golsB){const a=Number(prompt(`Pênaltis — ${j.timeA.nome}:`));const b=Number(prompt(`Pênaltis — ${j.timeB.nome}:`));if(!Number.isFinite(a)||!Number.isFinite(b)||a===b)return msg('Informe um resultado válido de pênaltis, sem empate.');payload.penaltisA=a;payload.penaltisB=b}try{await api(`${BASE_URL}/jogo/${jogoId}/finalizar`,{method:'POST',body:JSON.stringify(payload)});await load();msg('Partida encerrada com sucesso.')}catch(e){msg(e.message)}}
async function load(){if(!jogoId||!token)throw new Error('Link da Mesa inválido.');render(await api(`${BASE_URL}/jogo/${jogoId}/mesa?token=${encodeURIComponent(token)}`))}function connect(){const es=new EventSource(`${BASE_URL}/jogo/${jogoId}/stream`);es.addEventListener('jogo-atualizado',()=>{clearTimeout(reloadTimer);reloadTimer=setTimeout(()=>load().catch(e=>msg(e.message)),120)})}
setInterval(()=>{$('clock').textContent=fmt(nowClock())},1000);document.addEventListener('DOMContentLoaded',()=>{$('pickA').onclick=()=>selectTeam(cache.jogo.timeAId);$('pickB').onclick=()=>selectTeam(cache.jogo.timeBId);$('btnIniciar').onclick=()=>clock(cache?.jogo?.statusOperacao==='AO_VIVO'?'RETOMAR':'INICIAR');$('btnPausar').onclick=()=>clock('PAUSAR');$('btnIntervalo').onclick=()=>clock('INTERVALO');$('btnSegundoTempo').onclick=()=>clock('SEGUNDO_TEMPO');$('btnUndo').onclick=undo;$('btnEncerrar').onclick=finish;$('btnSub').onclick=()=>{const r=roster(),opts=r.map(p=>`<option value="${p.id}">${esc(p.nome)}</option>`).join('');$('jogadorSai').innerHTML='<option value="">Quem sai?</option>'+opts;$('jogadorEntra').innerHTML='<option value="">Quem entra?</option>'+opts;openModal('subModal')};$('confirmSub').onclick=()=>{const s=Number($('jogadorSai').value),e=Number($('jogadorEntra').value);if(!s||!e||s===e)return msg('Selecione jogadores diferentes.');closeModals();addEvent('SUBSTITUICAO',{jogadorId:null,jogadorSaindoId:s,jogadorEntrandoId:e})};$('btnObs').onclick=()=>openModal('obsModal');$('confirmObs').onclick=()=>{const detalhe=$('obsTexto').value.trim();if(!detalhe)return;closeModals();$('obsTexto').value='';addEvent('OBSERVACAO',{timeId:null,jogadorId:null,detalhe})};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModals);load().then(connect).catch(e=>msg(e.message))});
