-- AlterTable
ALTER TABLE `campeonato` ADD COLUMN `categoria` ENUM('ADULTO', 'SUB_15', 'SUB_17', 'SUB_20', 'FEMININO', 'AMADOR', 'PROFISSIONAL', 'OUTRO') NOT NULL DEFAULT 'ADULTO',
    ADD COLUMN `dataFim` DATETIME(3) NULL,
    ADD COLUMN `dataInicio` DATETIME(3) NULL,
    ADD COLUMN `modalidade` ENUM('FUTEBOL', 'FUTSAL', 'SOCIETY', 'ESPORTS', 'OUTRO') NOT NULL DEFAULT 'SOCIETY',
    ADD COLUMN `regulamentoTexto` VARCHAR(191) NULL,
    ADD COLUMN `regulamentoUrl` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('EM_CRIACAO', 'INSCRICOES_ABERTAS', 'EM_ANDAMENTO', 'FINALIZADO') NOT NULL DEFAULT 'EM_CRIACAO',
    ADD COLUMN `temporada` VARCHAR(191) NULL,
    MODIFY `tipo` ENUM('PONTOS_CORRIDOS', 'MATA_MATA', 'GRUPOS', 'GRUPOS_MATA_MATA', 'LIGA_IDA_VOLTA', 'COPA') NOT NULL;

-- CreateIndex
CREATE INDEX `Campeonato_status_idx` ON `Campeonato`(`status`);
