const {PrismaClient}=require('@prisma/client');
const prisma=new PrismaClient();
const TYPES=['PLAYER','DONO_TIME'];
const cardSelect={id:true,nome:true,fotoUrl:true,bio:true,posicaoCampo:true,modalidade:true,tipo:true};
const profileSelect={...cardSelect,pernaMelhor:true,timeRelacionado:{select:{id:true,nome:true,brasao:true,statusVinculo:true,society:{select:{id:true,nome:true}}}},times:{where:{statusVinculo:'APROVADO'},select:{id:true,nome:true,brasao:true,society:{select:{id:true,nome:true}}},orderBy:{nome:'asc'}},_count:{select:{seguidores:true,seguindo:true}}};
function idOf(v){const n=Number(v);return Number.isInteger(n)&&n>0&&n<=2147483647?n:null;}
function paging(req){const take=Number(req.query.take??24),cursor=Number(req.query.cursor??0);return Number.isInteger(take)&&take>=1&&take<=48&&Number.isInteger(cursor)&&cursor>=0&&cursor<=2147483647?{take,cursor}:null;}
function social(actor){return actor?.kind==='USER'&&TYPES.includes(actor.tipo);}
async function snapshot(id,actor){
 const user=await prisma.usuario.findFirst({where:{id,tipo:{in:TYPES}},select:profileSelect});if(!user)return null;
 let seguindo=false,segueVoce=false;
 if(social(actor)&&actor.id!==id){const edges=await prisma.usuarioSeguidor.findMany({where:{OR:[{seguidorId:actor.id,seguidoId:id},{seguidorId:id,seguidoId:actor.id}]},select:{seguidorId:true}});seguindo=edges.some(e=>e.seguidorId===actor.id);segueVoce=edges.some(e=>e.seguidorId===id);}
 const {timeRelacionado,times:owned,_count,...publicUser}=user;
 const times=[...(timeRelacionado?.statusVinculo==='APROVADO'?[timeRelacionado]:[]),...owned].filter((t,i,a)=>a.findIndex(x=>x.id===t.id)===i).map(({statusVinculo,...t})=>t);
 return {...publicUser,times,contadores:{seguidores:_count.seguidores,seguindo:_count.seguindo},seguindo,segueVoce,proprioPerfil:actor?.kind==='USER'&&actor.id===id,podeSeguir:social(actor)&&actor.id!==id};
}
function fail(res,e){console.error('perfil jogador',e);return res.status(e.code==='P2003'?404:500).json({error:e.code==='P2003'?'Jogador não encontrado.':'Não foi possível carregar a comunidade.'});}
async function read(req,res){const id=idOf(req.params.id);if(!id)return res.status(400).json({error:'Jogador inválido.'});try{const data=await snapshot(id,req.actor);return data?res.set('Cache-Control','no-store').json(data):res.status(404).json({error:'Perfil de jogador não encontrado.'});}catch(e){return fail(res,e);}}
async function list(req,res){const page=paging(req);if(!page)return res.status(400).json({error:'Paginação inválida.'});try{const q=String(req.query.q||'').trim().slice(0,100);const rows=await prisma.usuario.findMany({where:{tipo:{in:TYPES},id:{gt:page.cursor},...(q?{nome:{contains:q,mode:'insensitive'}}:{})},select:cardSelect,take:page.take+1,orderBy:{id:'asc'}});const usuarios=rows.slice(0,page.take);return res.set('Cache-Control','no-store').json({usuarios,nextCursor:rows.length>page.take?usuarios.at(-1).id:null});}catch(e){return fail(res,e);}}
async function connections(req,res){const id=idOf(req.params.id),page=paging(req),tipo=req.query.tipo||'seguidores';if(!id||!page||!['seguidores','seguindo'].includes(tipo))return res.status(400).json({error:'Filtro de conexões inválido.'});try{if(!await prisma.usuario.findFirst({where:{id,tipo:{in:TYPES}},select:{id:true}}))return res.status(404).json({error:'Jogador não encontrado.'});const inbound=tipo==='seguidores',key=inbound?'seguidorId':'seguidoId',relation=inbound?'seguidor':'seguido';const rows=await prisma.usuarioSeguidor.findMany({where:{[inbound?'seguidoId':'seguidorId']:id,[key]:{gt:page.cursor}},select:{[key]:true,[relation]:{select:cardSelect}},orderBy:{[key]:'asc'},take:page.take+1});const selected=rows.slice(0,page.take);return res.set('Cache-Control','no-store').json({usuarios:selected.map(r=>r[relation]),nextCursor:rows.length>page.take?selected.at(-1)[key]:null});}catch(e){return fail(res,e);}}
async function follow(req,res){const id=idOf(req.params.id);if(!id)return res.status(400).json({error:'Jogador inválido.'});if(!social(req.actor))return res.status(403).json({error:'Este recurso está disponível para jogadores e donos de time.'});if(id===req.actor.id)return res.status(400).json({error:'Você não pode seguir seu próprio perfil.'});try{if(!await prisma.usuario.findFirst({where:{id,tipo:{in:TYPES}},select:{id:true}}))return res.status(404).json({error:'Jogador não encontrado.'});const where={seguidorId:req.actor.id,seguidoId:id};if(req.method==='DELETE')await prisma.usuarioSeguidor.deleteMany({where});else await prisma.usuarioSeguidor.createMany({data:[where],skipDuplicates:true});const data=await snapshot(id,req.actor);return data?res.set('Cache-Control','no-store').json(data):res.status(404).json({error:'Jogador não encontrado.'});}catch(e){return fail(res,e);}}
module.exports={read,list,connections,follow};
